# Elasticsearch Configuration for JetStream Platform
# Version: 7.17.x
# Purpose: Production-grade Elasticsearch deployment with HA, security, and lifecycle management

# Cluster Configuration
cluster:
  name: jetstream-elasticsearch
  initial_master_nodes:
    - elasticsearch-master-0
  routing:
    allocation:
      awareness:
        attributes: zone
        force:
          zone.values: zone1,zone2,zone3
      disk:
        watermark:
          low: 85%
          high: 90%
          flood_stage: 95%

# Node Configuration
node:
  name: ${HOSTNAME}
  master: true
  data: true
  ingest: true
  max_local_storage_nodes: 1
  attr:
    zone: ${NODE_ZONE}

# Network Settings
network:
  host: 0.0.0.0
  port: 9200
  publish_host: ${PUBLISH_HOST}
  tcp:
    no_delay: true
    keep_alive: true

# Discovery Configuration
discovery:
  seed_hosts:
    - elasticsearch-master-headless
  minimum_master_nodes: 2

# Security Settings (X-Pack)
xpack:
  security:
    enabled: true
    transport:
      ssl:
        enabled: true
        verification_mode: certificate
        keystore:
          path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
          password: ${KEYSTORE_PASSWORD}
        truststore:
          path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
          password: ${TRUSTSTORE_PASSWORD}
    audit:
      enabled: true
  
  monitoring:
    enabled: true
    collection:
      enabled: true
      interval: 10s
      cluster.stats.timeout: 10s

# Index Management
indices:
  memory:
    index_buffer_size: 30%
  lifecycle:
    policies:
      jetstream-policy:
        phases:
          hot:
            min_age: 0ms
            actions:
              rollover:
                max_age: 7d
                max_size: 50gb
          warm:
            min_age: 7d
            actions:
              shrink:
                number_of_shards: 1
              forcemerge:
                max_num_segments: 1
          cold:
            min_age: 30d
            actions:
              searchable_snapshot:
                snapshot_repository: jetstream_backup
          delete:
            min_age: 90d
            actions:
              delete: {}

# Bootstrap Settings
bootstrap:
  memory_lock: true
  system_call_filter: true

# Path Settings
path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs

# HTTP Settings
http:
  cors:
    enabled: true
    allow-origin: "https://*.flyusa.com"
    allow-methods: "OPTIONS, HEAD, GET, POST, PUT, DELETE"
    allow-headers: "X-Requested-With, Content-Type, Content-Length, Authorization"
  compression: true
  max_content_length: 100mb