apiVersion: v1
kind: Secret
metadata:
  name: jetstream-secrets
  namespace: jetstream
  labels:
    app: jetstream
    component: secrets
  annotations:
    # Automated rotation schedule for different secret types
    rotation-schedule: "database=90d,api-keys=30d,jwt=30d,ssl=365d"
    azure.keyvault/enabled: "true"
    azure.keyvault/secret-rotation: "enabled"
type: Opaque
stringData:
  # Main PostgreSQL Database Credentials
  MAIN_DB_USERNAME: "jetstream_app"
  MAIN_DB_PASSWORD: "${MAIN_DB_PASSWORD}"
  MAIN_DB_SSL_CERT: "${MAIN_DB_SSL_CERT}"
  MAIN_DB_SSL_KEY: "${MAIN_DB_SSL_KEY}"
  MAIN_DB_SSL_CA: "${MAIN_DB_SSL_CA}"
  
  # Main DB Replica Credentials
  MAIN_DB_REPLICA_USERNAME: "jetstream_readonly"
  MAIN_DB_REPLICA_PASSWORD: "${MAIN_DB_REPLICA_PASSWORD}"
  
  # TimescaleDB Credentials
  TSDB_USERNAME: "jetstream_timeseries"
  TSDB_PASSWORD: "${TSDB_PASSWORD}"
  TSDB_SSL_CERT: "${TSDB_SSL_CERT}"
  TSDB_SSL_KEY: "${TSDB_SSL_KEY}"
  TSDB_SSL_CA: "${TSDB_SSL_CA}"
  
  # Redis Credentials and SSL
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_SSL_CERT: "${REDIS_SSL_CERT}"
  REDIS_SSL_KEY: "${REDIS_SSL_KEY}"
  REDIS_SSL_CA: "${REDIS_SSL_CA}"
  
  # Microsoft Teams Integration
  TEAMS_CLIENT_ID: "${TEAMS_CLIENT_ID}"
  TEAMS_CLIENT_SECRET: "${TEAMS_CLIENT_SECRET}"
  TEAMS_TENANT_ID: "${TEAMS_TENANT_ID}"
  
  # Teams Channel Configuration
  TEAMS_CHANNEL_OPERATIONS_PRIMARY: "${TEAMS_CHANNEL_OPERATIONS_PRIMARY}"
  TEAMS_CHANNEL_OPERATIONS_BACKUP: "${TEAMS_CHANNEL_OPERATIONS_BACKUP}"
  TEAMS_CHANNEL_SALES_PRIMARY: "${TEAMS_CHANNEL_SALES_PRIMARY}"
  TEAMS_CHANNEL_SALES_BACKUP: "${TEAMS_CHANNEL_SALES_BACKUP}"
  TEAMS_CHANNEL_CUSTOMER_SERVICE_PRIMARY: "${TEAMS_CHANNEL_CUSTOMER_SERVICE_PRIMARY}"
  TEAMS_CHANNEL_CUSTOMER_SERVICE_BACKUP: "${TEAMS_CHANNEL_CUSTOMER_SERVICE_BACKUP}"
  TEAMS_CHANNEL_MANAGEMENT_PRIMARY: "${TEAMS_CHANNEL_MANAGEMENT_PRIMARY}"
  TEAMS_CHANNEL_MANAGEMENT_BACKUP: "${TEAMS_CHANNEL_MANAGEMENT_BACKUP}"
  TEAMS_CHANNEL_EMERGENCY_PRIMARY: "${TEAMS_CHANNEL_EMERGENCY_PRIMARY}"
  TEAMS_CHANNEL_EMERGENCY_BACKUP: "${TEAMS_CHANNEL_EMERGENCY_BACKUP}"
  
  # JWT Authentication
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  JWT_REFRESH_KEY: "${JWT_REFRESH_KEY}"
  JWT_ACCESS_TOKEN_EXPIRATION: "30m"
  JWT_REFRESH_TOKEN_EXPIRATION: "7d"
  
  # Azure AD B2C Configuration
  AZURE_AD_CLIENT_ID: "${AZURE_AD_CLIENT_ID}"
  AZURE_AD_CLIENT_SECRET: "${AZURE_AD_CLIENT_SECRET}"
  AZURE_AD_TENANT_ID: "${AZURE_AD_TENANT_ID}"
  AZURE_B2C_POLICY_NAME: "B2C_1_jetstream_signin"
  AZURE_B2C_AUTHORITY_HOST: "https://jetstreamb2c.b2clogin.com"
  
  # Database Connection Pool Settings
  DB_POOL_CONFIG: |
    {
      "main": {
        "max_connections": "20",
        "min_connections": "5",
        "idle_timeout": "30000"
      },
      "timescale": {
        "max_connections": "30",
        "min_connections": "10",
        "idle_timeout": "20000"
      }
    }
  
  # Redis Cluster Configuration
  REDIS_CLUSTER_CONFIG: |
    {
      "max_redirects": "3",
      "retry_strategy": {
        "max_retries": "3",
        "base_delay": "200",
        "max_delay": "2000"
      }
    }