apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: jetstream-notification
  labels:
    app: notification-service
    component: backend
    part-of: jetstream
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: jetstream
    app.kubernetes.io/component: notification
    app.kubernetes.io/version: 1.0.0
    istio-injection: enabled
  annotations:
    # Monitoring configuration
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
    # Service mesh configuration
    service.istio.io/canonical-name: "notification-service"
    service.istio.io/canonical-revision: "v1"
    sidecar.istio.io/inject: "true"
    security.istio.io/tlsMode: "strict"
spec:
  type: ClusterIP
  ports:
    - name: http-api
      port: 3000
      targetPort: 3000
      protocol: TCP
      appProtocol: http
  selector:
    app: notification-service
    component: backend
  sessionAffinity: None
  publishNotReadyAddresses: false
  # Security and reliability settings
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4