apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: jetstream-api
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: jetstream
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/version: "1.0.0"
    istio.io/rev: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
    service.istio.io/canonical-name: api-gateway
    service.istio.io/canonical-revision: "v1"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 3000
      protocol: TCP
      name: https
  selector:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: jetstream
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/version: "1.0.0"