apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: jetstream
  labels:
    app: jetstream
    component: web
    part-of: jetstream-platform
    tier: frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http-web
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: jetstream
    component: web
  sessionAffinity: None
  publishNotReadyAddresses: false