apiVersion: apps/v1
kind: Deployment
metadata:
  name: aircraft-tracking
  namespace: jetstream-tracking
  labels:
    app: aircraft-tracking
    component: tracking
    part-of: jetstream
    version: 1.0.0
    tier: backend
  annotations:
    sidecar.istio.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: aircraft-tracking
  template:
    metadata:
      labels:
        app: aircraft-tracking
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: aircraft-tracking
        image: jetstream/aircraft-tracking:latest
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        - name: websocket
          containerPort: 3001
          protocol: TCP
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: TSDB_HOST
          valueFrom:
            secretKeyRef:
              name: jetstream-secrets
              key: TSDB_HOST
        - name: TSDB_PORT
          valueFrom:
            secretKeyRef:
              name: jetstream-secrets
              key: TSDB_PORT
        - name: TSDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: jetstream-secrets
              key: TSDB_USERNAME
        - name: TSDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jetstream-secrets
              key: TSDB_PASSWORD
        - name: TSDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: jetstream-secrets
              key: TSDB_DATABASE
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jetstream-secrets
              key: REDIS_PASSWORD
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
        - name: tmp
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: jetstream-tracking-config
      - name: secrets
        secret:
          secretName: jetstream-secrets
      - name: tmp
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - aircraft-tracking
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60