apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trip-management-hpa
  namespace: jetstream
  labels:
    app: trip-management
    component: backend
    part-of: jetstream
    managed-by: kubernetes
    scaling-policy: auto
  annotations:
    monitoring.jetstream.io/scaling-metrics: cpu,memory
    scaling.jetstream.io/last-modified: '2024-01-01'
    scaling.jetstream.io/review-period: quarterly
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trip-management
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
      selectPolicy: Min